Archive_Management/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import reverse_lazy
from django.views.generic import RedirectView


urlpatterns = [
    url(r'^$', RedirectView.as_view(url=reverse_lazy('user:index')), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^archive/', include('archive.urls')),
    # url(r'^api/', include('api.urls')),
    url(r'^user/', include('user.urls')),
    # url(r'^polls/', include('polls.urls')),
]

archive/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

app_name = 'archive'

urlpatterns = [
    # table list
    url(r'^TECH-archives/$', view=views.TechArchivesListView.as_view(), name='TECH-archives'),
    url(r'^GA-archives/$', view=views.GAArchivesListView.as_view() , name='GA-archives'),
    url(r'^ADM-archives/$', view=views.ADMArchivesListView.as_view() , name='ADM-archives'),

    # chart
    url(r'^chart-archives/$', TemplateView.as_view(template_name='archive/chart.html'), name='chart-archives'),

    # look content online
    url(r'^content/$', view=views.content, name='content'),

    # upload archive
    url(r'^upload/$', view=views.upload, name='upload'),
    url(r'^add/$', view=views.add, name='add'),

    # update archive
    url(r'^update_techarchive/$', view=views.update_techarchive, name='update_techarchive'),
    url(r'^update_GAarchive/$', view=views.update_GAarchive, name='update_GAarchive'),
    url(r'^update_ADMarchive/$', view=views.update_ADMarchive, name='update_ADMarchive'),

    url(r'^modify/$', view=views.modify, name='modify'),

    # delete archive
    url(r'^delete/$', view=views.delete, name='delete'),

]

user/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

app_name = 'user'

urlpatterns = [
    url(r'^$', view=TemplateView.as_view(template_name='user/login.html'), name='index'),

    url(r'^login/$', view=views.login, name='login'),
    url(r'^users/$', view=TemplateView.as_view(template_name='user/users.html'), name='users'),

    # edit user info
    url(r'^edit/$', view=views.edit, name='edit'),
    url(r'^modify/$', view=views.modify, name='modify'),


    # calendar and memo
    url(r'^calendar/$', view=views.calendar, name='calendar'),
    url(r'^MemoAdd/$', view=views.MemoAddView.as_view(), name='MemoAdd'),
    url(r'^MemoEdit/$', view=views.MemoEditView.as_view(), name='MemoEdit'),
    url(r'^MemoDel/$', view=views.MemoDelView.as_view(), name='MemoDel'),


    url(r'^logout/$', view=views.logout, name='logout'),
]

archive/models.py
from django.db import models
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone
# Create your models here.
class Archive(models.Model):
    title = models.CharField(max_length=512, default='blank')
    author = models.CharField(max_length=128, default='admin')
    content = models.TextField(null=True)

    classify = models.CharField(max_length=256, default='common')
    sub_classify = models.CharField(max_length=256, default='common')


    create_date = models.DateField(auto_now_add=True)
    modify_date = models.DateField(auto_now=True)

    star_count = models.IntegerField(default=0)
    read_count = models.IntegerField(default=0)
    download_count = models.IntegerField(default=0)


    def __repr__(self):
        return f'Title: {self.title}, Author: {self.author}'
    __str__ = __repr__

    class Meta:
        db_table = 'archives'

archive/views.py
from django.shortcuts import render, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.views.generic import View
from .models import Archive
from .forms import UploadFileForm
from user.login_check import LoginRequiredMixin, login_required

# Create your views here.

# List archives
class TechArchivesListView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        try:
            archive = Archive.objects.filter(classify='tech')[:1]
            type = archive[0].classify
        except:
            return render(request, 'user/404.html')

        context = {
            'techarchives': Archive.objects.filter(classify='tech'),
            'type': type
        }

        return render(request, 'archive/tech.html', context)

class ADMArchivesListView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        try:
            archive = Archive.objects.filter(classify='ADM')[:1]
            type = archive[0].classify
        except:
            return render(request, 'user/404.html')

        context = {
            'ADMarchives': Archive.objects.filter(classify='ADM'),
            'type': type
        }
        return render(request, 'archive/ADM.html', context)


class GAArchivesListView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        try:
            archive = Archive.objects.filter(classify='GA')[:1]
            type = archive[0].classify
        except:
            return render(request, 'user/404.html')

        context = {
            'GAarchives': Archive.objects.filter(classify='GA'),
            'type': type
        }
        return render(request, 'archive/GA.html', context)


# content
@login_required
def content(request):
    id = request.GET.get('id', -1)
    try:
        archive = Archive.objects.get(id=id)
        archive.read_count += 1
        archive.save()
    except ObjectDoesNotExist as e:
        print('This archive does not exist.')
    context = {
        'title': archive.title,
        'location': '/static/archives_store/' + archive.title + '.pdf',
    }
    print(context['location'])
    return render(request, 'archive/content.html', context)



# delete
@login_required
def delete(request):
    id = request.GET.get('id', -1)
    try:
        archive = Archive.objects.get(id=id)
        type = archive.classify
        archive.delete()
    except ObjectDoesNotExist as e:
        print('This archive does not exist.')
        return render(request, 'user/404.html')

    if type == "tech":
        return redirect('archive:TECH-archives')
    if type == "GA":
        return redirect('archive:GA-archives')
    if type == "ADM":
        return redirect('archive:ADM-archives')



# update
@login_required
def update_techarchive(request):
    id = request.GET.get('id', -1)

    context = {}

    return render(request, 'archive/update.html', context)



@login_required
def update_GAarchive(request):
    pass

@login_required
def update_ADMarchive(request):
    pass


@login_required
def modify(request):
    pass



# upload
@login_required
def upload(request):
    type = request.GET.get('type', '')

    context = {}
    context['type'] = type
    # add subclass here

    return render(request, 'archive/upload.html', context)


@login_required
def add(request):
    type = request.POST.get('archivetype')
    time = request.POST.get('archivecreatetime')
    title = request.POST.get('archivetitle')

    file = request.FILES['archivefile']

    handle_upload_file(file, str(file))

    Archive.objects.create(title=title, author=time, classify=type)

    if type == "tech":
        return redirect('archive:TECH-archives')
    if type == "GA":
        return redirect('archive:GA-archives')
    if type == "ADM":
        return redirect('archive:ADM-archives')


def handle_upload_file(file, filename):
    path = '/root/Archive_Management/static/archives_store/'
    with open(path+filename,'wb+') as destination:
        for chunk in file.chunks():
            destination.write(chunk)

archive/templates/archive/ADM.html
{% extends 'layout.html' %}
{% load static %}
{% block link %}
    <link rel="stylesheet" href="{% static 'DataTables-1.10.15/media/css/dataTables.jqueryui.css' %}">
    <link rel="stylesheet" href="{% static 'DataTables-1.10.15/media/css/jquery.dataTables.css' %}">
{% endblock %}
{% block data-type %}widgets{% endblock %}
{% block content %}
        <div class="tpl-content-wrapper">
            <div class="row-content am-cf">
                <div class="row">
                    <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">
                        <div class="widget am-cf">
                            <div class="widget-head am-cf">
                                <div class="widget-title  am-cf">行政档案
                                    <a class="am-btn am-btn-success am-btn-xs" href="/archive/upload/?type={{ type }}" style="margin-left: 20px;">新增</a>
                                </div>
                            </div>
                            <div class="widget-body  am-fr">
                                <div class="am-u-sm-12">
                                    <table width="100%" class="am-table am-table-compact am-table-striped tpl-table-black" id="ADM-archives">
                                        <thead>
                                            <tr>
                                                <th width="200" style="text-align: center;">文章标题</th>
                                                <th width="100">子类</th>
                                                <th width="120">时间</th>
                                                <th style="display: none" width="100">内容</th>
                                                <th width="150">操作</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for archive in ADMarchives %}
                                            <tr class="gradeX" style="background-color: darkslategrey;">
                                                <td>{{ archive.title }}</td>
                                                <td>{{ archive.sub_classify }}</td>
                                                <td>{{ archive.create_date }}</td>
                                                <td style="display: none;">更支持通过全文搜索查询您想要的档案信息，并以丰富的图表展示档案使用情况</td>
                                                <td>
                                                    <div class="tpl-table-black-operation">
                                                        <a href="/archive/content/?id={{ archive.id }}" >
                                                            <i class="am-icon-arrows"></i> 预览
                                                        </a>
                                                        <a href="/archive/update_ADMarchive/?id={{ archive.id }}">
                                                            <i class="am-icon-pencil"></i> 更新版本
                                                        </a>
                                                        <a href="/archive/delete/?id={{ archive.id }}" class="tpl-table-black-operation-del">
                                                            <i class="am-icon-trash"></i> 删除
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            {% endfor %}
                                            <!-- more data -->
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}
{% block script %}
    <script src="{% static 'DataTables-1.10.15/media/js/jquery.dataTables.js' %}"></script>
    <script  src="{% static 'DataTables-1.10.15/media/js/dataTables.jqueryui.js' %}"></script>
{% endblock %}
{% block js %}
    $('#ADM-archives').DataTable({
        language: {
            url: "{% static 'json/DataTables.i18n.zh_cn.json' %}"
        }
    });
{% endblock %}

archive/templates/archive/GA.html
{% extends 'layout.html' %}
{% load static %}
{% block link %}
    <link rel="stylesheet" href="{% static 'DataTables-1.10.15/media/css/dataTables.jqueryui.css' %}">
    <link rel="stylesheet" href="{% static 'DataTables-1.10.15/media/css/jquery.dataTables.css' %}">
{% endblock %}
{% block data-type %}widgets{% endblock %}
{% block content %}
        <div class="tpl-content-wrapper">
            <div class="row-content am-cf">
                <div class="row">
                    <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">
                        <div class="widget am-cf">
                            <div class="widget-head am-cf">
                                <div class="widget-title  am-cf">总务档案
                                    <a class="am-btn am-btn-success am-btn-xs" href="/archive/upload/?type={{ type }}" style="margin-left: 20px;">新增</a>
                                </div>
                            </div>
                            <div class="widget-body  am-fr">
                                <div class="am-u-sm-12">
                                    <table width="100%" class="am-table am-table-compact am-table-striped tpl-table-black" id="GA-archives">
                                        <thead>
                                            <tr>
                                                <th width="200" style="text-align: center;">文章标题</th>
                                                <th width="100">子类</th>
                                                <th width="120">时间</th>
                                                <th width="100" style="display: none">内容</th>
                                                <th width="150">操作</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for archive in GAarchives %}
                                            <tr class="gradeX" style="background-color: darkslategrey;">
                                                <td>{{ archive.title }}</td>
                                                <td>{{ archive.sub_classify }}</td>
                                                <td>{{ archive.create_date }}</td>
                                                <td style="display: none">大巴黎VS皇家马德里</td>
                                                <td>
                                                    <div class="tpl-table-black-operation">
                                                        <a href="/archive/content/?id={{ archive.id }}" >
                                                            <i class="am-icon-arrows"></i> 预览
                                                        </a>
                                                        <a href="/archive/update_GAarchive/?id={{ archive.id }}">
                                                            <i class="am-icon-pencil"></i> 更新版本
                                                        </a>
                                                        <a href="/archive/delete/?id={{ archive.id }}" class="tpl-table-black-operation-del">
                                                            <i class="am-icon-trash"></i> 删除
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                            {% endfor %}
                                            <!-- more data -->
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}
{% block script %}
    <script src="{% static 'DataTables-1.10.15/media/js/jquery.dataTables.js' %}"></script>
    <script  src="{% static 'DataTables-1.10.15/media/js/dataTables.jqueryui.js' %}"></script>
{% endblock %}
{% block js %}
    $('#GA-archives').DataTable({
        language: {
            url: "{% static 'json/DataTables.i18n.zh_cn.json' %}"
        }
    });
{% endblock %}

archive/templates/archive/chart.html
{% extends 'layout.html' %}
{% block data-type %}chart{% endblock %}
{% block content %}
        <div class="tpl-content-wrapper">

            <div class="container-fluid am-cf">
                <div class="row">
                    <div class="am-u-sm-12 am-u-md-12 am-u-lg-9">
                        <div class="page-header-heading"><span class="am-icon-picture-o page-header-heading-icon"></span> 图表 <small>Archives Management</small></div>
                        <p class="page-header-description">展示的是Archives Management使用情况、档案新增信息、档案变更信息等的统计情况图表。</p>
                    </div>
                </div>

            </div>

            <div class="row-content am-cf">
                <div class="widget am-cf">
                    <div class="widget-head am-cf">
                        <div class="widget-title am-fl">折线图</div>
                        <div class="widget-function am-fr">
                            <a href="javascript:;" class="am-icon-cog"></a>
                        </div>
                    </div>
                    <div class="widget-body am-fr">
                        <div style="height: 400px" class="" id="tpl-echarts-A">

                        </div>
                    </div>
                </div>


                <div class="widget am-cf">
                    <div class="widget-head am-cf">
                        <div class="widget-title am-fl">雷达图</div>
                        <div class="widget-function am-fr">
                            <a href="javascript:;" class="am-icon-cog"></a>
                        </div>
                    </div>
                    <div class="widget-body am-fr">
                        <div style="height: 400px" id="tpl-echarts-B">

                        </div>
                    </div>
                </div>


                <div class="widget am-cf">
                    <div class="widget-head am-cf">
                        <div class="widget-title am-fl">折线柱图</div>
                        <div class="widget-function am-fr">
                            <a href="javascript:;" class="am-icon-cog"></a>
                        </div>
                    </div>
                    <div class="widget-body am-fr">
                        <div style="height: 400px" id="tpl-echarts-C">

                        </div>
                    </div>
                </div>

            </div>
        </div>
{% endblock %}

archive/templates/archive/content.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
   <div>
      <h2 style="color: darkgrey;">{{ title }}</h2>
   </div>
   <div style="margin-left: 100px;padding-left: 120px;">
      <a class="media" href="{{ location }}"></a>
   </div>
{% endblock %}
{% block script %}
    <script type="application/javascript" src="{% static 'jquery-3.2.1/jquery.media.js' %}"></script>
{% endblock %}
{% block js %}
    $(function() {
        $('a.media').media({width:1200, height:700});
    });
{% endblock %}

archive/templates/archive/update.html
{% extends 'layout.html' %}
{% load static %}
{% block data-type %}widgets{% endblock %}
{% block content %}

<div class="tpl-content-wrapper">
    <div class="row-content am-cf">
        <div class="row">
            <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">
                <div class="widget am-cf">
                    <div class="widget-head am-cf">
                        <div class="widget-title am-fl">新增档案</div>
                        <div class="widget-function am-fr">
                            <a href="javascript:;" class="am-icon-cog"></a>
                        </div>
                    </div>
                    <div class="widget-body am-fr">
<table class="am-table" width="20%">
    <h2>版本变更历史</h2>
    <thead>
        <tr>
            <th>网站名称</th>
            <th>网址</th>
            <th>创建时间</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Amaze UI</td>
            <td>http://amazeui.org</td>
            <td>2012-10-01</td>
        </tr>
        <tr>
            <td>Amaze UI</td>
            <td>http://amazeui.org</td>
            <td>2012-10-01</td>
        </tr>
        <tr >
            <td>Amaze UI(Active)</td>
            <td>http://amazeui.org</td>
            <td>2012-10-01</td>
        </tr>
        <tr>
            <td>Amaze UI</td>
            <td>http://amazeui.org</td>
            <td>2012-10-01</td>
        </tr>
        <tr>
            <td>Amaze UI</td>
            <td>http://amazeui.org</td>
            <td>2012-10-01</td>
        </tr>
    </tbody>
</table>
                        <form class="am-form tpl-form-border-form tpl-form-border-br" method="POST" action="{% url 'archive:modify' %}" enctype="multipart/form-data" accept-charset="UTF-8">
                            {% csrf_token %}
                            <div class="am-form-group">
                                <label for="archive-title" class="am-u-sm-3 am-form-label">标题 <span class="tpl-form-line-small-title">Title</span></label>
                                <div class="am-u-sm-9">
                                    <input type="text" class="tpl-form-input" id="archive-title" name="archive-title" placeholder="请输入完整的档案标题">
                                    <small>请输入完整的档案标题</small>
                                </div>
                            </div>

                            <input type="hidden" class="tpl-form-input" id="archive-type" name="archive-type" value="{{ type }}">

                            <div class="am-form-group">
                                <label for="archive-author" class="am-u-sm-3 am-form-label">作者 <span class="tpl-form-line-small-title">Author</span></label>
                                <div class="am-u-sm-9">
                                    <input type="text" class="am-form-field tpl-form-no-bg" id="archive-author" name="archive-author" placeholder="请输入作者">
                                    <small>请输入作者</small>
                                </div>
                            </div>

                            <div class="am-form-group">
                                <label for="archive-subclass" class="am-u-sm-3 am-form-label">子类 <span class="tpl-form-line-small-title">Subclass</span></label>
                                <div class="am-u-sm-9">
                                    <select data-am-selected="{searchBox: 1}" style="display: none;" id="archive-subclass" name="archive-subclass">
                                      <option value="a">-The.CC</option>
                                      <option value="b">夕风色</option>
                                      <option value="o">Orange</option>
                                    </select>

                                </div>
                            </div>

                            <div class="am-form-group">
                                <label for="archive-file" class="am-u-sm-3 am-form-label">附件 <span class="tpl-form-line-small-title">File</span></label>
                                <div class="am-u-sm-9">
                                    <input type="file" class="am-form-field tpl-form-no-bg" id="archive-file" name="archive-file" placeholder="选择附件上传">
                                    <small>选择附件上传</small>
                                </div>
                            </div>



                            <div class="am-form-group">
                                <div class="am-u-sm-9 am-u-sm-push-3">
                                    <button type="submit" class="am-btn am-btn-primary tpl-btn-bg-color-success ">提交</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

archive/templates/archive/upload.html
{% extends 'layout.html' %}
{% load static %}
{% block data-type %}widgets{% endblock %}
{% block content %}
<div class="tpl-content-wrapper">
    <div class="row-content am-cf">
        <div class="row">
            <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">
                <div class="widget am-cf">
                    <div class="widget-head am-cf">
                        <div class="widget-title am-fl">新增档案</div>
                        <div class="widget-function am-fr">
                            <a href="javascript:;" class="am-icon-cog"></a>
                        </div>
                    </div>
                    <div class="widget-body am-fr">

                        <form class="am-form tpl-form-border-form tpl-form-border-br" method="POST" action="{% url 'archive:add' %}" enctype="multipart/form-data" accept-charset="UTF-8">
                            {% csrf_token %}
                            <div class="am-form-group">
                                <label for="archivetitle" class="am-u-sm-3 am-form-label">标题 <span class="tpl-form-line-small-title">Title</span></label>
                                <div class="am-u-sm-9">
                                    <input type="text" class="tpl-form-input" id="archive-title" name="archivetitle" placeholder="请输入完整的档案标题">
                                    <small>请输入完整的档案标题</small>
                                </div>
                            </div>

                            <input type="hidden" class="tpl-form-input" id="archive-type" name="archivetype" value="{{ type }}">


                            <div class="am-form-group">
                                <label for="archivesubclass" class="am-u-sm-3 am-form-label">子类 <span class="tpl-form-line-small-title">Subclass</span></label>
                                <div class="am-u-sm-9">
                                    <select data-am-selected="{searchBox: 1}" style="display: none;" id="archivesubclass" name="archivesubclass">
                                      <option value="a">-The.CC</option>
                                      <option value="b">夕风色</option>
                                      <option value="o">Orange</option>
                                    </select>
                                </div>
                            </div>

                            <div class="am-form-group">
                                <label for="archivecreatetime" class="am-u-sm-3 am-form-label">发布时间 <span class="tpl-form-line-small-title">Time</span></label>
                                <div class="am-u-sm-9">
                                    <input type="text" class="am-form-field tpl-form-no-bg" placeholder="发布时间" data-am-datepicker="" readonly="" name="archivecreatetime">
                                    <small>发布时间为必填</small>
                                </div>
                            </div>

                            <div class="am-form-group">
                                <label for="archivefile" class="am-u-sm-3 am-form-label">附件 <span class="tpl-form-line-small-title">File</span></label>
                                <div class="am-u-sm-9">
                                    <input type="file" class="am-form-field tpl-form-no-bg" id="archive-file" name="archivefile" placeholder="选择附件上传">
                                    <small>选择附件上传</small>
                                </div>
                            </div>



                            <div class="am-form-group">
                                <div class="am-u-sm-9 am-u-sm-push-3">
                                    <button type="submit" class="am-btn am-btn-primary tpl-btn-bg-color-success ">提交</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}