Archive_Management/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import reverse_lazy
from django.views.generic import RedirectView


urlpatterns = [
    url(r'^$', RedirectView.as_view(url=reverse_lazy('user:index')), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^archive/', include('archive.urls')),
    # url(r'^api/', include('api.urls')),
    url(r'^user/', include('user.urls')),
    # url(r'^polls/', include('polls.urls')),
]

user/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

app_name = 'user'

urlpatterns = [
    url(r'^$', view=TemplateView.as_view(template_name='user/login.html'), name='index'),

    url(r'^login/$', view=views.login, name='login'),
    url(r'^users/$', view=TemplateView.as_view(template_name='user/users.html'), name='users'),

    # edit user info
    url(r'^edit/$', view=views.edit, name='edit'),
    url(r'^modify/$', view=views.modify, name='modify'),


    # calendar and memo
    url(r'^calendar/$', view=views.calendar, name='calendar'),
    url(r'^MemoAdd/$', view=views.MemoAddView.as_view(), name='MemoAdd'),
    url(r'^MemoEdit/$', view=views.MemoEditView.as_view(), name='MemoEdit'),
    url(r'^MemoDel/$', view=views.MemoDelView.as_view(), name='MemoDel'),


    url(r'^logout/$', view=views.logout, name='logout'),
]

user/models.py
from django.db import models
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone
from .auth import auth_user
# Create your models here.

class User(models.Model):
    name = models.CharField(max_length=256)
    nickname = models.CharField(max_length=256, default='Newer')

    profile_picture = models.CharField(max_length=128, default='user04.png')

    email = models.EmailField(null=True)
    register_time = models.DateField(auto_now_add=True)


    role = models.CharField(max_length=256, default='undistributed')
    temp_role = models.CharField(max_length=256, null=True)

    @classmethod
    def login(cls, name, password):
        username = 'xib\\' + name
        ret = auth_user(username, password)

        # password correct
        if ret:
            try:
                user = User.objects.get(name=name)
                return user
            except ObjectDoesNotExist as e:
                user = User()
                user.name = name
                user.save()
                return user

        # password error
        else:
            return None



    class Meta:
        db_table = 'users'

    def __repr__(self):
        return f'Name: {self.name}, Role: {self.role}'

    __str__ = __repr__


class Record(models.Model):
    user = models.ForeignKey(User)

    file = models.CharField(max_length=256, default='blank')
    action = models.CharField(max_length=128, default='')

    message = models.CharField(max_length=512, default='')

    time = models.DateTimeField(auto_now_add=True)

    def __repr__(self):
        return f'User: {self.user.name}, Action: {self.action}, Message: {self.message}'

    __str__ = __repr__

    class Meta:
        db_table = 'records'


class Memo(models.Model):
    user = models.ForeignKey(User)
    title = models.CharField(max_length=512, default='')
    startday = models.CharField(max_length=128, default='')
    endday = models.CharField(max_length=128, default='')

    def __repr__(self):
        return f'User: {self.user.name}, MemoTitle: {self.title}'

    __str__ = __repr__


    class Meta:
        db_table = 'memos'

user/views.py
import datetime
from django.shortcuts import render, redirect
from django.http.response import JsonResponse
from django.core.exceptions import ObjectDoesNotExist
from django.views.generic import View, ListView
from .login_check import login_required, LoginRequiredMixin


from .models import User, Record, Memo
# Create your views here.



def login(request):
    name = request.POST.get('username')
    password = request.POST.get('userpassword')
    user = User.login(name, password)

    if user:
        location = '/static/user_profile_picture/' + user.profile_picture
        request.session['user'] = {'name': user.name, 'id': user.id, 'nickname': user.nickname, 'location': location}
        return redirect('user:users')
    else:
        context = {}
        context['name'] = name
        context['error'] = '用户名或密码错误'
        return render(request, 'user/login.html', context)

@login_required
def edit(request):
    return render(request, 'user/edit.html')

@login_required
def modify(request):
    id = request.POST.get('id', -1)
    nickname = request.POST.get('usernickname', '')
    profileimage = request.FILES['userprofileimage']


    User.objects.filter(id=id).update(nickname=nickname, profile_picture=str(profileimage))
    handle_upload_file(profileimage, str(profileimage))

    return redirect("user:users")


def handle_upload_file(file, filename):
    path = '/root/Archive_Management/static/user_profile_picture/'
    with open(path+filename,'wb+') as destination:
        for chunk in file.chunks():
            destination.write(chunk)

# calendar
@login_required
def calendar(request):
    uid = request.session['user'].get('id', -1)
    date = datetime.datetime.now()

    context = {'memos': Memo.objects.filter(user_id=uid), 'time': date.strftime('%Y-%m-%d')}
    return render(request, 'user/calendar.html', context)


class MemoAddView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        uid = request.POST.get('user_id', -1)
        title = request.POST.get('title', '')
        startday = request.POST.get('startday', '')
        endday = request.POST.get('endday', '')

        Memo.objects.create(user_id=uid, title=title, startday=startday, endday=endday)

        return JsonResponse({'code': 200, 'text': 'success', 'result': None, 'errors':{}})

class MemoEditView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        id = request.POST.get('memo_id', -1)
        title = request.POST.get('memo_title', '')


        Memo.objects.filter(id=id).update(title=title)

        return JsonResponse({'code': 200, 'text': 'success', 'result': None, 'errors':{}})


class MemoDelView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        id = request.POST.get('memo_id', -1)

        Memo.objects.filter(id=id).delete()

        return JsonResponse({'code': 200, 'text': 'success', 'result': None, 'errors':{}})


def logout(request):
    request.session.flush()

    return redirect('user:index')

user/templates/user/calendar.html
{% extends 'layout.html' %}
{% load static %}
{% block link %}
    <link rel="stylesheet" href="{% static 'sweetalert/dist/sweetalert.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/fullcalendar.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/fullcalendar.print.css' %}" media='print' />
{% endblock %}
{% block data-type %}widgets{% endblock %}
{% block content %}
    <div class="tpl-content-wrapper">
            <div class="row-content am-cf">
                <div class="tpl-calendar-box">
                    <div id="calendar">
                    </div>
                </div>

            </div>
    </div>

        <div class="am-modal am-modal-no-btn" id="calendar-edit-box">
        <div class="am-modal-dialog tpl-model-dialog">
            <div class="am-modal-hd">
                <a href="javascript: void(0)" class="am-close edit-box-close am-close-spin" data-am-modal-close>&times;</a>
            </div>
            <div class="am-modal-bd tpl-am-model-bd am-cf">

                <form class="am-form tpl-form-border-form" action="#" method="POST">
                    {% csrf_token %}
                    <div class="am-form-group am-u-sm-12">
                        <label for="content" class="am-u-sm-12 am-form-label am-text-left">标题 <span class="tpl-form-line-small-title">Title</span></label>
                        <div class="am-u-sm-12">
                            <input type="text" class="tpl-form-input am-margin-top-xs calendar-edit-box-title" id="content" placeholder="">
                        </div>

                        <div class="am-u-sm-12">
                            <input type="hidden" class="tpl-form-input am-margin-top-xs calendar-edit-box-id" placeholder="">
                        </div>

                        <div class="am-u-sm-12" style="text-align: right;">
                            <button type="button" class="am-btn am-btn-danger btn-del" data-dismiss="modal">删除</button>
                            <button type="button" class="am-btn am-btn-success btn-save">保存</button>
                        </div>
                    </div>

                </form>

            </div>
        </div>
    </div>

    <script>
        $(document).ready(function() {
            var editBox = $('#calendar-edit-box');
            var uid  = {{ request.session.user.id }};
            $('.edit-box-close').on('click', function() {
                $('#calendar').fullCalendar('unselect');
            })

            $('#calendar').fullCalendar({

                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'month,agendaWeek,agendaDay'
                },

                monthNames: ["一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月", "十月", "十一月", "十二月"],
                monthNamesShort: ["一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月", "十月", "十一月", "十二月"],
                dayNames: ["星期日", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六"],
                dayNamesShort: ["星期日", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六"],
                today: ["今天"],
                firstDay: 1,
                buttonText: {
                    today: '本月',
                    month: '月',
                    week: '周',
                    day: '日',
                    prev: '上一月',
                    next: '下一月'
                },
                defaultDate: '{{ time }}',
                lang: 'zh-cn',
                navLinks: true, // can click day/week names to navigate views
                selectable: true,
                selectHelper: true,
                select: function(start, end) {
                    swal({
                      title: "Archives Management",
                      text: "在此处填写你要记录的事",
                      type: "input",
                      showCancelButton: true,
                      closeOnConfirm: false,
                      animation: "slide-from-top",
                      inputPlaceholder: "输入一些话..."
                    },
                    function(inputValue){
                      if (inputValue === false) return false;

                      if (inputValue === "") {
                        swal.showInputError("你需要输入一些话！");
                        return false
                      }


                      $.post("{% url 'user:MemoAdd' %}", {'user_id': uid, 'title': inputValue, 'startday': start.format(), 'endday': end.format()}, function(response){
                            if (response['code'] == 200){
                                swal({ title: "信息添加成功", type: "success", showCancelButton: false, confirmButtonText: "确定", closeOnConfirm: false }, function(){window.location.reload();});
                            }
                      }, 'json')




                    });





                },




                editable: true,
                eventLimit: true, // allow "more" link when too many events
                eventClick: function(event, jsEvent, view) {

                    // event.source.events[0].title = '222223333'
                    // 修改数据
                    // 标题
                    $('.calendar-edit-box-id').val(event.id);
                    $('.calendar-edit-box-title').val(event.title);



                    editBox.modal();
                },




                // 数据区
                events: [
                    {% for memo in memos %}
                    {
                        id: {{ memo.id }},
                        title: '{{ memo.title }}',
                        start: '{{ memo.startday }}',
                        end: '{{ memo.endday }}'
                    },
                    {% endfor %}
                ]

            });

            $('button.btn-del').click(function(){
              var id = $('.calendar-edit-box-id').val()
              $.post("{% url 'user:MemoDel' %}", {'memo_id': id }, function(response){
                    if (response['code'] == 200){
                        swal({ title: "信息删除成功", type: "success", showCancelButton: false, confirmButtonText: "确定", closeOnConfirm: false }, function(){window.location.reload();});
                    }
              }, 'json')
            });

            $('button.btn-save').click(function(){
              var id = $('.calendar-edit-box-id').val()
              var title = $('.calendar-edit-box-title').val()

              $.post("{% url 'user:MemoEdit' %}", {'memo_id': id, 'memo_title': title }, function(response){
                    if (response['code'] == 200){
                        swal({ title: "信息更新成功", type: "success", showCancelButton: false, confirmButtonText: "确定", closeOnConfirm: false }, function(){window.location.reload();});
                    }
              }, 'json')
            });


        });
    </script>
{% endblock %}
{% block script %}
    <script src="{% static 'sweetalert/dist/sweetalert.min.js' %}"></script>
{% endblock %}

user/templates/user/edit.html
{% extends 'layout.html' %}
{% load static %}
{% block data-type %}widgets{% endblock %}
{% block content %}
    <div class="tpl-content-wrapper">
        <div class="row-content am-cf">
                <div class="row">
                    <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">
                        <div class="widget am-cf">
                            <div class="widget-head am-cf">
                                <div class="widget-title am-fl">编辑用户信息</div>
                                <div class="widget-function am-fr">
                                    <a href="javascript:;" class="am-icon-cog"></a>
                                </div>
                            </div>
                            <div class="widget-body am-fr">

                                <form class="am-form tpl-form-border-form tpl-form-border-br" method="POST" action="{% url 'user:modify' %}" enctype="multipart/form-data" accept-charset="UTF-8">
                                    {% csrf_token %}

                                    <input type="hidden" name="id" value="{{ request.session.user.id }}">

                                    <div class="am-form-group">
                                        <label for="usernickname" class="am-u-sm-3 am-form-label">昵称 <span class="tpl-form-line-small-title">Nickname</span></label>
                                        <div class="am-u-sm-9">
                                            <input type="text" class="tpl-form-input" id="usernickname" name="usernickname" placeholder="请输入您的昵称">
                                            <small>来起一个好听的昵称吧</small>
                                        </div>
                                    </div>

                                    <div class="am-form-group">
                                        <label for="userprofileimage" class="am-u-sm-3 am-form-label">头像 <span class="tpl-form-line-small-title">User Image</span></label>
                                        <div class="am-u-sm-9">
                                            <input type="file" class="am-form-field tpl-form-no-bg" id="userprofileimage" name="userprofileimage" placeholder="选择附件上传">
                                            <small>推荐使用像素100X100的图片</small>
                                        </div>
                                    </div>

                                    <div class="am-form-group">
                                        <div class="am-u-sm-9 am-u-sm-push-3">
                                            <button type="submit" class="am-btn am-btn-primary tpl-btn-bg-color-success ">提交</button>
                                        </div>
                                    </div>

                                    <div class="am-form-group">
                                        <label for="usernickname" class="am-u-sm-3 am-form-label"><span class="tpl-form-line-small-title"></span></label>
                                        <div class="am-u-sm-9">
                                            <input type="text" class="tpl-form-input"  placeholder="下次登录时生效" disabled>
                                        </div>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
    </div>
{% endblock %}

user/templates/user/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Login</title>
    <meta name="description" content="">
    <meta name="keywords" content="index">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="renderer" content="webkit">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <link rel="icon" type="image/png" href="{% static 'assets/i/favicon.png' %}">
    <link rel="apple-touch-icon-precomposed" href="{% static 'assets/i/app-icon72x72@2x.png' %}">
    <meta name="apple-mobile-web-app-title" content="" />
    <link rel="stylesheet" href="{% static 'assets/css/amazeui.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/amazeui.datatables.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/app.css' %}">
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>

</head>

<body data-type="login">
    <script src="{% static 'assets/js/theme.js' %}"></script>
    <div class="am-g tpl-g">
        <!-- 风格切换 -->
        <div class="tpl-skiner">
            <div class="tpl-skiner-toggle am-icon-cog"></div>
            <div class="tpl-skiner-content">
                <div class="tpl-skiner-content-title">
                    选择主题
                </div>
                <div class="tpl-skiner-content-bar">
                    <span class="skiner-color skiner-white" data-color="theme-white"></span>
                    <span class="skiner-color skiner-black" data-color="theme-black"></span>
                </div>
            </div>
        </div>
        <div class="tpl-login">
            <div class="tpl-login-content">

                    <h1 style="color: darkgrey;text-align: center;">Archives Management</h1>



                <form class="am-form tpl-form-line-form" action="{% url 'user:login' %}" method="POST">
                    {% csrf_token %}
                    <div class="am-form-group">
                        <input type="text" class="tpl-form-input" value="{{ name }}" placeholder="请输入账号" name="username">
                    </div>

                    <div class="am-form-group">
                        <input type="password" class="tpl-form-input" autocomplete="off" placeholder="请输入密码" name="userpassword">
                    </div>
{#                    <div class="am-form-group tpl-login-remember-me">#}
{#                        <input id="remember-me" type="checkbox">#}
{#                        <label for="remember-me">#}
{##}
{#                        记住密码#}
{#                         </label>#}
{##}
{#                    </div>#}
                    {% if error %}
                        <span style="color: red;">{{ error }}</span>
                    {% endif %}
                    <div class="am-form-group">
                        <button type="submit" class="am-btn am-btn-primary  am-btn-block tpl-btn-bg-color-success  tpl-login-btn">登录</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script src="{% static 'assets/js/amazeui.min.js' %}"></script>
    <script src="{% static 'assets/js/app.js' %}"></script>

</body>

</html>