Archive_Management/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import reverse_lazy
from django.views.generic import RedirectView


urlpatterns = [
    url(r'^$', RedirectView.as_view(url=reverse_lazy('user:index')), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^archive/', include('archive.urls')),
    # url(r'^api/', include('api.urls')),
    url(r'^user/', include('user.urls')),
    # url(r'^polls/', include('polls.urls')),
]

archive/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

app_name = 'archive'

urlpatterns = [
    # table list
    url(r'^TECH-archives/$', view=views.TechArchivesListView.as_view(), name='TECH-archives'),
    url(r'^GA-archives/$', view=views.GAArchivesListView.as_view() , name='GA-archives'),
    url(r'^ADM-archives/$', view=views.ADMArchivesListView.as_view() , name='ADM-archives'),

    # chart
    url(r'^chart-archives/$', TemplateView.as_view(template_name='archive/chart.html'), name='chart-archives'),

    # look content online
    url(r'^content/$', view=views.content, name='content'),

    # upload archive
    url(r'^upload/$', view=views.upload, name='upload'),
    url(r'^add/$', view=views.add, name='add'),

    # update archive
    url(r'^update_techarchive/$', view=views.update_techarchive, name='update_techarchive'),
    url(r'^update_GAarchive/$', view=views.update_GAarchive, name='update_GAarchive'),
    url(r'^update_ADMarchive/$', view=views.update_ADMarchive, name='update_ADMarchive'),

    url(r'^modify/$', view=views.modify, name='modify'),

    # delete archive
    url(r'^delete/$', view=views.delete, name='delete'),

]

user/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

app_name = 'user'

urlpatterns = [
    url(r'^$', view=TemplateView.as_view(template_name='user/login.html'), name='index'),

    url(r'^login/$', view=views.login, name='login'),
    url(r'^users/$', view=TemplateView.as_view(template_name='user/users.html'), name='users'),

    # edit user info
    url(r'^edit/$', view=views.edit, name='edit'),
    url(r'^modify/$', view=views.modify, name='modify'),


    # calendar and memo
    url(r'^calendar/$', view=views.calendar, name='calendar'),
    url(r'^MemoAdd/$', view=views.MemoAddView.as_view(), name='MemoAdd'),
    url(r'^MemoEdit/$', view=views.MemoEditView.as_view(), name='MemoEdit'),
    url(r'^MemoDel/$', view=views.MemoDelView.as_view(), name='MemoDel'),


    url(r'^logout/$', view=views.logout, name='logout'),
]

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Archives Management</title>
    <meta name="description" content="">
    <meta name="keywords" content="index">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="renderer" content="webkit">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <meta name="apple-mobile-web-app-title" content="Amaze UI" />
    <link rel="icon" type="image/png" href="{% static 'assets/i/favicon.png' %}">
    <link rel="apple-touch-icon-precomposed" href="{% static 'assets/i/app-icon72x72@2x.png' %}">
    <link rel="stylesheet" href="{% static 'assets/css/amazeui.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/amazeui.datatables.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/app.css' %}">
    {% block link %}{% endblock %}
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/echarts.min.js' %}"></script>
</head>

<body data-type="{% block data-type %}{% endblock %}">
    <script src="{% static 'assets/js/theme.js' %}"></script>
    <div class="am-g tpl-g">
        <!-- 头部 -->
        <header>
            <!-- logo -->
            <div class="am-fl tpl-header-logo">
                <h2 style="color: darkgrey;margin-top: 15px; margin-left: 15px; text-align: left;">档案管理系统</h2>
            </div>
            <!-- 右侧内容 -->
            <div class="tpl-header-fluid">
                <!-- 侧边切换 -->
                <div class="am-fl tpl-header-switch-button am-icon-list">
                <span>
                </span>
                </div>
                <!-- 搜索 -->
{#                <div class="am-fl tpl-header-search">#}
{#                    <form class="tpl-header-search-form" action="javascript:;">#}
{#                        <button class="tpl-header-search-btn am-icon-search"></button>#}
{#                        <input class="tpl-header-search-box" type="text" placeholder="搜索内容...">#}
{#                    </form>#}
{#                </div>#}
                <!-- 其它功能-->
                <div class="am-fr tpl-header-navbar">
                    <ul>
                        <!-- 欢迎语 -->
                        <li class="am-text-sm tpl-header-navbar-welcome">
                            <a href="javascript:;">欢迎你, <span>{{ request.session.user.name }}</span> </a>
                        </li>

{#                        <!-- 新消息，新上传档案或更新版本 -->#}
{#                        <li class="am-dropdown tpl-dropdown" data-am-dropdown>#}
{#                            <a href="#" class="am-dropdown-toggle tpl-dropdown-toggle" data-am-dropdown-toggle>#}
{#                                <i class="am-icon-envelope"></i>#}
{#                                <span class="am-badge am-badge-success am-round item-feed-badge">4</span>#}
{#                            </a>#}
{#                            <!-- 弹出列表 -->#}
{#                            <ul class="am-dropdown-content tpl-dropdown-content">#}
{##}
{#                                <li class="tpl-dropdown-menu-messages">#}
{#                                    <a href="javascript:;" class="tpl-dropdown-menu-messages-item am-cf">#}
{#                                        <div class="menu-messages-ico">#}
{#                                            <img src="{% static 'assets/img/user04.png' %}" alt="">#}
{#                                        </div>#}
{#                                        <div class="menu-messages-time">#}
{#                                            3小时前#}
{#                                        </div>#}
{#                                        <div class="menu-messages-content">#}
{#                                            <div class="menu-messages-content-title">#}
{#                                                <i class="am-icon-circle-o am-text-success"></i>#}
{#                                                <span>夕风色</span>#}
{#                                            </div>#}
{#                                            <div class="am-text-truncate"> Amaze UI 的诞生，依托于 GitHub 及其他技术社区上一些优秀的资源；Amaze UI 的成长，则离不开用户的支持。 </div>#}
{#                                            <div class="menu-messages-content-time">2016-09-21 下午 16:40</div>#}
{#                                        </div>#}
{#                                    </a>#}
{#                                </li>#}
{##}
{#                                <li class="tpl-dropdown-menu-messages">#}
{#                                    <a href="#" class="tpl-dropdown-menu-messages-item am-cf">#}
{#                                        <i class="am-icon-circle-o"></i> 进入列表…#}
{#                                    </a>#}
{#                                </li>#}
{#                            </ul>#}
{#                        </li>#}


{#                        <!-- 新提醒，工作流待办事项-->#}
{#                        <li class="am-dropdown" data-am-dropdown>#}
{#                            <a href="javascript:;" class="am-dropdown-toggle" data-am-dropdown-toggle>#}
{#                                <i class="am-icon-bell"></i>#}
{#                                <span class="am-badge am-badge-warning am-round item-feed-badge">5</span>#}
{#                            </a>#}
{##}
{#                            <!-- 弹出列表 -->#}
{#                            <ul class="am-dropdown-content tpl-dropdown-content">#}
{#                                <li class="tpl-dropdown-menu-notifications">#}
{#                                    <a href="javascript:;" class="tpl-dropdown-menu-notifications-item am-cf">#}
{#                                        <div class="tpl-dropdown-menu-notifications-title">#}
{#                                            <i class="am-icon-line-chart"></i>#}
{#                                            <span> 有6笔新的销售订单</span>#}
{#                                        </div>#}
{#                                        <div class="tpl-dropdown-menu-notifications-time">#}
{#                                            12分钟前#}
{#                                        </div>#}
{#                                    </a>#}
{#                                </li>#}
{#                                <li class="tpl-dropdown-menu-notifications">#}
{#                                    <a href="javascript:;" class="tpl-dropdown-menu-notifications-item am-cf">#}
{#                                        <div class="tpl-dropdown-menu-notifications-title">#}
{#                                            <i class="am-icon-star"></i>#}
{#                                            <span> 有3个来自人事部的消息</span>#}
{#                                        </div>#}
{#                                        <div class="tpl-dropdown-menu-notifications-time">#}
{#                                            30分钟前#}
{#                                        </div>#}
{#                                    </a>#}
{#                                </li>#}
{#                                <li class="tpl-dropdown-menu-notifications">#}
{#                                    <a href="javascript:;" class="tpl-dropdown-menu-notifications-item am-cf">#}
{#                                        <div class="tpl-dropdown-menu-notifications-title">#}
{#                                            <i class="am-icon-folder-o"></i>#}
{#                                            <span> 上午开会记录存档</span>#}
{#                                        </div>#}
{#                                        <div class="tpl-dropdown-menu-notifications-time">#}
{#                                            1天前#}
{#                                        </div>#}
{#                                    </a>#}
{#                                </li>#}
{##}
{##}
{#                                <li class="tpl-dropdown-menu-notifications">#}
{#                                    <a href="javascript:;" class="tpl-dropdown-menu-notifications-item am-cf">#}
{#                                        <i class="am-icon-bell"></i> 进入列表…#}
{#                                    </a>#}
{#                                </li>#}
{#                            </ul>#}
{#                        </li>#}

                        <!-- 退出 -->
                        <li class="am-text-sm">
                            <a href="{% url 'user:logout' %}">
                                <span class="am-icon-sign-out"></span> 退出
                            </a>
                        </li>
                    </ul>
                </div>
            </div>

        </header>
        <!-- 风格切换 -->
        <div class="tpl-skiner">
            <div class="tpl-skiner-toggle am-icon-cog">
            </div>
            <div class="tpl-skiner-content">
                <div class="tpl-skiner-content-title">
                    选择主题
                </div>
                <div class="tpl-skiner-content-bar">
                    <span class="skiner-color skiner-white" data-color="theme-white"></span>
                    <span class="skiner-color skiner-black" data-color="theme-black"></span>
                </div>
            </div>
        </div>
        <!-- 侧边导航栏 -->
        <div class="left-sidebar">
            <!-- 用户信息 -->
            <div class="tpl-sidebar-user-panel">
                <div class="tpl-user-panel-slide-toggleable">
                    <div class="tpl-user-panel-profile-picture">
                        <img src="{{ request.session.user.location }}" alt="">
                    </div>
                    <span class="user-panel-logged-in-text">

{#                        judge gender#}
                        <i class="am-icon-circle-o am-text-success tpl-user-panel-status-icon"></i>
                        
                      {{ request.session.user.nickname }}
                    </span>
                    <a href="{% url 'user:edit' %}" class="tpl-user-panel-action-link"> <span class="am-icon-pencil"></span> 账号设置</a>
                </div>
            </div>

            <!-- 菜单 -->
            <ul class="sidebar-nav">
                <li class="sidebar-nav-heading">Components <span class="sidebar-nav-heading-info"> 功能导航栏</span></li>
                <li class="sidebar-nav-link">
                    <a href="{% url 'user:users' %}" class="active">
                        <i class="am-icon-home sidebar-nav-link-logo"></i> 首页
                    </a>
                </li>

                <li class="sidebar-nav-link">
                    <a href="javascript:;" class="sidebar-nav-sub-title">
                        <i class="am-icon-table sidebar-nav-link-logo"></i> 档案列表
                        <span class="am-icon-chevron-down am-fr am-margin-right-sm sidebar-nav-sub-ico"></span>
                    </a>
                    <ul class="sidebar-nav sidebar-nav-sub">
                        <li class="sidebar-nav-link">
                            <a href="{% url 'archive:GA-archives' %}">
                                <span class="am-icon-angle-right sidebar-nav-link-logo"></span> 总务档案
                            </a>
                        </li>

                        <li class="sidebar-nav-link">
                            <a href="{% url 'archive:TECH-archives' %}">
                                <span class="am-icon-angle-right sidebar-nav-link-logo"></span> 科技档案
                            </a>
                        </li>

                        <li class="sidebar-nav-link">
                            <a href="{% url 'archive:ADM-archives' %}">
                                <span class="am-icon-angle-right sidebar-nav-link-logo"></span> 行政档案
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="sidebar-nav-link">
                    <a href="{% url 'archive:chart-archives' %}">
                        <i class="am-icon-bar-chart sidebar-nav-link-logo"></i> 图表
                    </a>
                </li>

                <li class="sidebar-nav-link">
                    <a href="{% url 'user:calendar' %}">
                        <i class="am-icon-calendar sidebar-nav-link-logo"></i> 事件管理
                    </a>
                </li>
            </ul>
        </div>
        <!-- 内容区域 -->
        {% block content %}{% endblock %}
</div>

    <script src="{% static 'assets/js/amazeui.min.js' %}"></script>
    <script src="{% static 'assets/js/amazeui.datatables.min.js' %}"></script>
    <script src="{% static 'assets/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'assets/js/moment.js' %}"></script>
    <script src="{% static 'assets/js/fullcalendar.min.js' %}"></script>
    <script src="{% static 'assets/js/app.js' %}"></script>
    {% block script %}{% endblock %}
    <script type="application/javascript">
        {% block js %}{% endblock %}
    </script>
</body>
</html>